name: "PowerShell Script Analyzer"

on:
  push:
    branches:
      - 'main'
      - 'development'
      - 'stable'
      - 'release/v*'
      - 'feature/*'
      - 'issue/*'
    paths-ignore:
      - '.github/workflows/*'
      - '**/*.md'
      - '**/*.txt'
  pull_request:
    branches:
      - 'main'
      - 'stable'
      - 'development'
      - 'release/v*'

permissions:
  contents: read

jobs:
  analyzer:
    name: Analyze PowerShell
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read
    uses: dafneb/.github/.github/workflows/powershell-analyzer.yml@73cd59b01daa56d6d1db5d99379cb525f9a448a7 # v1.4.2
    secrets: inherit
