name: "PowerShell Script Analyzer"

on:
  push:
    branches:
      - 'main'
      - 'development'
      - 'stable'
      - 'release/v*'
      - 'feature/*'
      - 'issue/*'
    paths-ignore:
      - '.github/workflows/*'
      - '**/*.md'
      - '**/*.txt'
  pull_request:
    branches:
      - 'main'
      - 'stable'
      - 'development'
      - 'release/v*'

permissions:
  contents: read

jobs:
  analyzer:
    name: Analyze PowerShell
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read
    uses: dafneb/.github/.github/workflows/powershell-analyzer.yml@2447bb5e1b5f31b2c534e3590cdc543a93576db2 # v1.2.2
    secrets: inherit
