name: Assign Pull Request Creator

on:
  pull_request:
    types: 
      - opened
      - reopened
    branches:
      - 'main'
      - 'stable'
      - 'release/v*'

jobs:
  assign-assignees:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Assign PR creator
        uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ github.actor }}
